### ISSUE TITLE
Introduce check versus list mode

### ISSUE THREAD

**Issue by guibou** [guibou/krank#31]
For now, `krank` is just listing open and close github issues.

We should introduce a mode with a command line argument `--mode` with options:

- `check`: will only display `closed` issues and fails if it exists any closed issue
- `list`: will list all issues (closed or open).

**Comment by guibou** [comment]
@gbataille since #42 ignored issues are removed from the list. In `list` mode, they should still appear, but with an `info` or `warning` status.

**Comment by guibou** [comment]
All of that is not really important until we had more tests, so we'll be able to specify the semantic.

**Comment by guibou** [comment]
@gbataille I've opened #58 which introduce a `--fail-on-error` flag: `krank` now exits with a failure if there is any "error". However I'd like to discuss a bit the semantic. Hopefully we'll get something smart before merging.

- Should `krank` fails by default or not? I do think so. ~That's not the case right now in #58~ Done in #58.
- We have two kinds of error. Linter error, such as a closed issue, and "runtime" error, like when `krank` cannot read a text file, or cannot do a network request, or if a network request fails unexpectedly. What should we do for the runtime error? Should we reclassify them as error and fail too? I do think that yes. Should we return different exit code. For example:
  - 0: no error
  - 1: only lint error
  - 2: only runtime error
  - 3: both lint error and runtime error. #58 only fails. We'll improve later if needed.
- We need not to fail on `krank:ignore` issues which are now closed, but what to do with issues which are tagged as `krank:ignore` and which are not closed. Why the user decided to ignore it? Was it closed, then reopened and it may need a look from the user? Right now nothing is done in #58. I'll open new issues for that.

**Comment by gbataille** [comment]
hum.

- #58 ok
- yes for both types of errors. maybe rather than having 1/2/3 we should have a "composable" return code that is a bit field. (Well 1, 2 and 3 could be the start of the bit field :D)
- not very important but interesting --> different issue?

For the overall issue, I'm not at ease.  
Yes it's interesting, but then reporting on github/gitlab/... issue is not the only purpose of `krank`.  
I would say
1. for sure it's not a priority (with respect to handling other linter like bitrotting todo for example)
2. maybe that should be a different executable, or at least the CLI argument should clearly states that only one/some checkers are going to run, in a special mode
