### ISSUE TITLE
Could diffcheck be a krank?

### ISSUE THREAD

**Issue by jameshaydon** [guibou/krank#71]
Hi, this is a great project!

I have made [diffcheck](https://github.com/jameshaydon/diff-check) which has some similarities to this project. It seems most related to these goals: #2 and #5.

It's still quite primitive, but I've found it to already be somewhat useful. There are many ways it should be extended, e.g. as you note in those issues I will probably and begin/end-markers.

I think it would be nice to try and make diffcheck one of the checkers of `krank`. If there is interest in this, I can start to think about making `diffcheck` match `krank`'s checker API.

Without looking too deeply there are already a few things it does differently:
- It parses a git diff in order to detect edits that might require checking,
- It has an interactive mode to mark a check as checked. This might be interesting for other krank checkers: a checker might `Maybe` suggest a possible resolution action for each violation, e.g. delete stale comment line.

**Comment by guibou** [comment]
@jameshaydon Thank you for your message.

`diffcheck` is a really nice project.

I'd really love to add more checker to `krank` what you check with `diffcheck` are really part of the todo list.

I'm totally fine with checks which parse `git` results. For example, look at #3, I'd like to parse `git blame` to know the "age" of a TODO.

I don't really know how the "interactive" interface of `diffcheck` fits in krank. However I do think that's a really good idea, it may be possible to provide a `quickfix` mode which fix stuffs which are fixable. However it is not as simple as it is in other tools, such as code formatter: the fix is never obvious nor unique. Take for example an old TODO or a link to a now closed github issue, removing them is part of the fix, but not the full fix.

Please, if you want to contribute with anything (code, design discussion, ideas), don't hesitate.

**Comment by guibou** [comment]
@jameshaydon I'm trying to reduce the scope of krank. see #86 for discussion.

In thi scontext, `diffcheck` won't be part of krank.
